name: HDX data series monthly updates

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run download and merge
      run: python scripts/4_merge_changes.py
      env:
        credentials: ${{ secrets.GOOGLE_AUTH }}
    - name: Update HDX for changes
      run: python scripts/5b_create_change_set_and_update.py
      env:
        HDX_auth: ${{ secrets.HDX_AUTH }}
    - name: Create summary output
      run: python scripts/6_data_series_summary.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit updated sources
      with:
        commit_message: automatic update of scrape
